linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    # - cyclop
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - gci
    # - gocognit
    - nestif
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - gosec
    - importas
    - makezero
    - misspell
    # - prealloc
    - promlinter
    - predeclared
    - nolintlint
    - revive
    - stylecheck
    - tagliatelle
    - thelper
    - unparam
    - unused
    - whitespace
    # - wrapcheck
linters-settings:
  gosec:
    excludes:
      - G404
  gocritic:
    disabled-checks:
      - ifElseChain
    enabled-tags:
      - performance
      - diagnostic
      - experimental
      - opinionated
  nestif:
    min-complexity: 8
