name: Go

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Jerome1337/goimports-action@v1.0.3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
  test:
    name: Test (1.17)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: go test -v -timeout=1s -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Test (race)
        run: go test -v -timeout=1s -race ./...
      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
  test-old:
    name: Test (1.16)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test
        run: go test -v -timeout=1s ./...
      - name: Test (race)
        run: go test -v -timeout=1s -race ./...
