name: Go

on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "cmd/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "cmd/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v2
  test:
    name: Test (latest major)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "~1.21.6"
      - name: Test
        run: go test -v -timeout=1s -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Test (race)
        run: go test -v -timeout=1s -race ./...
      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
  test-old:
    name: Test (previous major)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "~1.20.13"
      - name: Test
        run: go test -v -timeout=1s ./...
      - name: Test (race)
        run: go test -v -timeout=1s -race ./...
